apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-dev
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp-dev
  template:
    metadata:
      labels:
        app: flaskapp-dev
    spec:
      containers:
      - name: flaskapp-dev
        image: oriexsol/my_app:test
        imagePullPolicy: Always
        ports:
        - name: nodejs-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /isalive
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
---
  
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: flaskapp-dev
  type: NodePort

