apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-prod
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp-prod
  template:
    metadata:
      labels:
        app: flaskapp-prod
    spec:
      containers:
      - name: flaskapp-prod
        image: oriexsol/my_app:deploy
        imagePullPolicy: Always
        ports:
        - name: nodejs-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /isalive
            port: nodejs-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
---
  
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-p-service
  namespace: prod
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
    protocol: TCP
  selector:
    app: flaskapp-prod
  type: NodePort

